### ISSUE TITLE
2019

### ISSUE THREAD

**Issue by flytape8490** [DeborahK/CSharpBP-Collections#4]
Tests won't run and projects won't build with VisualStudio 2019, or dotnet 3.1.x.

For example, right-clicking the ProductName_JustRight test and running it as instructed in the Arrays: Discarding and Populating An Array video yields: 
"Could not load file or assembly 'file:///...AcmeApp\Tests\Acme.BizTests\bin\Debug\Acme.BizTests.dll' or one of its dependencies. Operation is not supported."
And if you navigate to that folder, the DLL is there so it's not clear what dependency is missing. Regardless, the tests won't run so the video can't be followed properly.

Other instances later in the video set, as seen in the attached screenshot, return much more complicated errors about how a container is missing.
![image](https://user-images.githubusercontent.com/7305915/76363901-03962280-62f2-11ea-9c31-4a5857740c57.png)

**Comment by DeborahK** [comment]
I opened the project in VS 2019. I ran the two UI projects without error. I also ran the tests without error:

![image](https://user-images.githubusercontent.com/7987365/76450925-d6964e00-638b-11ea-8691-07391d1df12e.png)

**Comment by flytape8490** [comment]
I did not.
I installed a fresh copy of VS into a virtual machine and I'm not having any issues, so i'm assuming it's something with the settings. 
Problem solved, sort-of?

**Comment by DeborahK** [comment]
OK. Closing this for now then. Thanks!
